### ISSUE TITLE
Database Design: Implement Controller Operations for Sell Action Table

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#100]
Objective:
Develop a controller for the Sell action, that will handle all CRUD operations (Create, Read, Update, Delete) for managing purchases within the application. Refer to the Item model implementation for this and following model and action implementations.

Requirements:

Implement methods for adding, retrieving, updating, and deleting purchase records.
Ensure thorough validation and error handling for each operation.
Completion Criteria:

Full CRUD functionality for the Sell action is developed and operational.
The controller successfully manages errors and validates input data.
Time Constraint:
Target completion by Friday, October 4.

Scoring:
Difficulty: 5
Urgency: 5

**Comment by YampierFernandez** [comment]
Checked controller and model in sell_model_implementation branch, approved for manager review.
