### ISSUE TITLE
Database Design: Order Event Entity Implementation

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#101]
Objective:

Design and implement the Order event entity to align with the overall database structure and ensure robust data management.
Requirements:

Design the Sell Action: Define the structure of the Order event entity, ensuring that it supports all required fields and relationships.

Define Parameters: Assign discussed parameters in the ERD to the Order event, considering data types, constraints, and relationships to other entities.

Completion Criteria:

TheOrder event table is fully defined, implemented, and integrated with the database.

The model includes all fields, data types, and constraints specified in the initial ERD.

Time Constraint:

Deadline: Friday, October 4
Scoring:

Urgency: 6

Difficulty: 5

**Comment by YampierFernandez** [comment]
The work was checked in the sell_model_implementation branch and approved for manager review.
