### ISSUE TITLE
Database Design: Implement Controller Operations for Order Event

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#102]
Objective:
Develop a controller for the Order, that will handle all CRUD operations (Create, Read, Update, Delete) for managing associations between users and the total price of their order. Refer to the Item model **controller** implementation for this and following model and action implementations.

Requirements:

Implement methods for adding, retrieving, updating, and deleting order records.
Ensure thorough validation and error handling for each operation.
Completion Criteria:

Full CRUD functionality for the Order event is developed and operational.
The controller successfully manages errors and validates input data.
Time Constraint:
Target completion by Friday, October 4.

Scoring:
Difficulty: 6
Urgency: 5

**Comment by AlvinBadillo** [comment]
Completed the implementation of the Order controller on the sell_model_implementation branch. This includes full CRUD functionality with input validation, error handling, and logging for improved debugging. The controller follows the structure of the Item controller to maintain consistency across the project. The Order controller is now ready for integration and testing.
