### ISSUE TITLE
Connect Database to Backend

### ISSUE THREAD

**Issue by franRov** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#108]
## Objective
•	Connect MongoDB Atlas database to the backend of our project, ensuring data flow between the frontend and database.

## Requirements
•	Establish a secure connection between the backend and MongoDB Atlas
•	Test data flow between frontend and backend to ensure seamless communication.
•	Create necessary API routes (e.g., /signup, /login) for user authentication and data storage.
•	Use environment variables to store sensitive credentials (e.g., connection URI, database credentials).

## Completion Criteria
•	MongoDB Atlas connected to the backend.
•	Frontend can interact with the backend to store and retrieve data.
•	Secure handling of database credentials using .env file.

## Time Constraint:
•	Monday, October 21

## Scoring:
•	Urgency: 5
•	Difficulty: 8

**Comment by franRov** [comment]
<img width="1470" alt="Screenshot 2024-10-20 at 8 01 44 PM" src="https://github.com/user-attachments/assets/840d7f53-084f-456e-aee3-70bef816d455">



## Overview
We have successfully established a connection to our project's database through the backend server and tested this integration using ThunderClient. A route has been set up for the item model to handle incoming and outgoing requests. This issue aims to outline the next steps required to expand our API to handle additional models and to ensure that all requests conform to the defined model guidelines.

## Achievements
- **Database Connection Established**: Connection to the MongoDB database has been successfully established and tested.
- **Item Model Route**: A route for the item model has been created and tested, ensuring it can receive and send requests as expected.

## Additional Tasks to be made
### 1. Create Routes for Additional Models
- We need to develop and test routes for the remaining models defined in our schema. This includes:
  - User model
  - Order model
  - etc...

### 2. Ensure Requests Adhere to Model Guidelines
- Review and ensure that all API requests for creating and updating entries follow the strict guidelines defined in our model schemas. This includes:
  - Validating incoming data formats
  - Ensuring required fields are not omitted
  - Implementing proper error handling and responses for invalid requests

**Comment by franRov** [comment]
The branch containing all of the code is in the 'Database' branch

**Comment by YampierFernandez** [comment]
After a meeting with the assignee I can can confirm his work and I approve for manager review.
