### ISSUE TITLE
Web UI: Create Cart Page

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#124]
Objective: 
> Create a page where the user can see products that were added to their cart. They will be able to see the button for checkout with the total as well.

Requirements:
> The products should be visible in a column showing the name, seller, cost and quantity of each product
> Total cost will be calculated according to the amount of products there are in the cart at the moment
> user will be able to add and remove products and total cost will be recalculated accordingly

Completion Criteria:
Submit a page with all the requirements mentioned. Push a file containing the coded page to the web UI branch. User is able to view the UI of the cart page.

Time Constraint:

Complete by Wednesday, October 9, 2024.

Difficulty Score: 6

Urgency Score: 6

**Comment by DiegoVazquez1** [comment]
Website-Frontend branch
