### ISSUE TITLE
Documentation: Revise sections 2.1.2 and 2.1.3

### ISSUE THREAD

**Issue by CovasJJ** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#125]
**Objective:**

- Revise sections "2.1.2- Terminology" and "2.1.3- Domain Terminology in relation to domain rough sketch" of the documentation to address the specific feedback provided by the professor.

**Requirements:** 

- Access documentation.
- Read the professor's feedback.
- Understand the subject and the professor's feedback to revise. 

**Completion Criteria:** 

- Revise sections 2.1.2 and 2.1.3 and make changes needed to achieve the goal. 
- Use the highlighting format in the documentation when making the changes, making the changes visible. 

**Time Constraint:**

- Complete by Wednesday, October 9, 2024.

Difficulty Score: 4
Urgency Score: 4

**Comment by elliot-gomez** [comment]
Here's the document of the Professor's feedback on the Milestone 1 Documentation compiled and organized: https://docs.google.com/document/d/1mgeaMFhLv9pnXXquTvetwGGvpln88BVpuJaQZQaXAmc/edit?usp=sharing

**Comment by CovasJJ** [comment]
I have completed the revision of these parts. All changes and edits have been added to the Google Docs.
