### ISSUE TITLE
Documentation: Revise sections 2.1.6

### ISSUE THREAD

**Issue by JuanDelPueblo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#126]
**Objective:**

- Revise section "2.1.6 Function Signatures" of the documentation to address the specific feedback provided by the professor.

**Requirements:** 

- Access the Milestone 2 documentation via Google Docs.
- Read and understand the professor's feedback.
- Apply the professor's feedback during revision of the section 2.1.6. 

**Completion Criteria:** 

- Revise section 2.1.6 and make all the changes needed to achieve the objective. 
- Use the correct highlighting format in the documentation while revising, making the changes visible. 

**Time Constraint:**

- Complete by Friday, October 25, 2024.

Difficulty Score: 5
Urgency Score: 4

**Comment by elliot-gomez** [comment]
Here's the document of the Professor's feedback on the Milestone 1 Documentation compiled and organized: https://docs.google.com/document/d/1mgeaMFhLv9pnXXquTvetwGGvpln88BVpuJaQZQaXAmc/edit?usp=sharing

**Comment by JuanDelPueblo** [comment]
I have finished integrating the professor's feedback on section 2.1.6
