### ISSUE TITLE
[Lecture Topic Task] Target user survey

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#129]
Objective:
Create, handle and carry out a survey that targets potential users of our system to be.

Requirements:
- Find samples of target users, some who have gone to Mercado Colegial, some who haven’t and some who run a stand or participate in carrying out the event.
- Write down a series of survey questions for the target users to answer. That could give us some insight of what the project needs and what its flaws are. 
- Carry out the survey, handing out the questions to target users and taking their answers as results. 
- Evaluate and analyze the results of the survey
- Write down or otherwise present your findings and conclusions: ( List of findings, paragraphs, graphs, etc. , But make sure to write the conclusions in paragraph or essay form)

Completion Criteria:
- Organized and readable document with all questions for the survey, and the answers collected with the name of the person who answered next to the answer.
- Organized and readable document containing the results and conclusions after evaluating and analyzing the results of the survey. (Could be a single document for both this and the previous criteria.) 

Time Constraint:
Sunday, October 20th. 

Urgency Level:
7
Difficulty:
10

**Comment by PerezMarcelo** [comment]
[Survey Analysis.pdf](https://github.com/user-attachments/files/17446698/Survey.Analysis.pdf)
**SURVEY ANALISIS**

**Comment by FabiolaZTorres** [comment]
The surveys were conducted by creating Google Forms with the questions agreed upon by the team and then approaching buyers and sellers at the Mercado Colegial to ask them to fill out the forms.

Buyer survey: https://forms.gle/wnFc4xYW6WAiHSjL7
Seller survey: https://forms.gle/2GmG8pT8AxjJb7NdA
