### ISSUE TITLE
Documentation: Revise Section 1.2.2 and General Document Changes

### ISSUE THREAD

**Issue by elliot-gomez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#131]
Objective:
Revise the section 1.2.2 of the documentation to address the specific feedback provided by the professor. Additionally, apply general changes across the document as per the professor's general feedback, such as changing the use of certain words or phrases.

Requirements:
- Access the Milestone 1 documentation via Google Docs.
- Read and understand the professor's feedback.
- Apply the professor's feedback during revision of the section 1.2.2 and document as a whole in regards to the general feedback.

Completion Criteria:
- Revise section 1.2.2 and make all the changes needed to address the feedback.
- Ensure that the revisions meet the professor's expectations and maintain the structure of the documentation.
- Use the correct highlighting format in the documentation while revising, making the changes visible.

Time Constraint: Complete by Wednesday, October 23, 2024

Difficulty Score: 4
Urgency Score: 4

**Comment by elliot-gomez** [comment]
Professor's feedback on the Milestone 1 Documentation compiled and organized: https://docs.google.com/document/d/1mgeaMFhLv9pnXXquTvetwGGvpln88BVpuJaQZQaXAmc/edit?usp=sharing

**Comment by elliot-gomez** [comment]
I’ve completed the revisions required of this task based on the professor's feedback. All changes, revisions, and edits are highlighted in green for easy reference. If you don’t have a copy of the original Milestone #1 documentation, I’ve attached it here in case you’d like to compare: https://docs.google.com/document/d/1_2llwwnDIMDuGr0lthQ8omcHlFlpFSf0qjE1pg8Ay7g/edit?usp=sharing

**Comment by elliot-gomez** [comment]
In addition to the section specific changes, I also made general wording changes throughout the document based on the professor's feedback on the original document. This included adjusting terminology like replacing "real-time" with "timely," simplifying user stories for clarity, and standardizing the use of "vendor" instead of alternating with "seller." I didn't highlight every single one of these instances because I thought it would be tedious, so that's why I'm mentioning it here.

**Comment by Christian2101** [comment]
Task was completed in the wrong milestone documentation. Please move those changes to the correct documentation. Here is the link: https://docs.google.com/document/d/1G125uRW48AgflDRd0anF54FlXE3FgT2U0IQbgWnHY2c/edit?usp=sharing

**Comment by elliot-gomez** [comment]
I’ve moved the changes to the correct milestone documentation as requested. Everything is now in place, and the revisions are highlighted properly according to the key for easy reference. Let me know if there’s anything else you need!
