### ISSUE TITLE
Database Design or Backend: REST API research 

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#142]
Objective:
Research REST API for backend of the application to have access to the database and the ability to modify it.

Requirements:
•	Find a suitable REST API that can serve as a way to connect the application directly to the database, and give the application access to the data via HTTP request.
•	The REST API must allow for request such as get, post, delete.
•	Provide light description and reasoning for choosing this REST API.

Completion Criteria:
•	State choice of a suitable REST API to be used for the project.
•	Provide a link with information on the chosen REST API (documentation or the API’s website would be best).
•	Write and provide description of the chosen REST API and some of the reasons for the choice. This should be a paragraph or two. 

Time Constraint:
Saturday, October 19th.

Urgency Level:
5
Difficulty:
2

**Comment by YampierFernandez** [comment]
My choice of REST API would be Thunder Client. The following link leads to their website with the documentation and directions to download the extension:

https://www.thunderclient.com/

Thunder client is a lightweight REST API that excels at simple and direct API testing. I choose it for three main reasons: It is downloaded as an extension for VScode and the setup is rather simple. I have had experience with Thunder Client before so it’s easier for me based on experience and I have more ways answering questions if they arise. Thunder client is designed with a focus on simplicity which I believe is good fit for our project.

**Comment by franRov** [comment]
I agree that Thunder Client is a strong choice for our project, especially when compared to Postman. Postman requires heavier setup and resource consumption can be overkill for our current needs.

Thunder Client's lightweight nature gives us the advantage of testing APIs without switching environments, which will streamline our workflow. The simplicity and focus on essential features also align well within our project’s scope.

Also, given that not everyone in our project has experience with client-server interaction, I believe this is the more user-friendly tool for our developers. We'll be moving forward with the Thunder Client API for this project.

Lead Reviewed.
