### ISSUE TITLE
Database Design: Review Model Creation 

### ISSUE THREAD

**Issue by AlvinBadillo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#144]
Objective: 
- Design and implement the Review entity model to align with the overall database structure and ensure robust data management.

Requirements:
- Design the Review Entity: Define the structure of the Review entity, ensuring that it supports all required fields and relationships.

Define Parameters: 
- Assign discussed parameters in the ERD to the Review entity, considering data types, constraints, and relationships to other entities.

Completion Criteria:
- The Review entity model is fully defined, implemented, and integrated with the database.

The model includes all fields, data types, and constraints specified in the initial ERD.

Time Constraint:
- Deadline: Wednesday, October 23

Scoring:
- Urgency: 5
- Difficulty: 4

**Comment by AlvinBadillo** [comment]
The Review entity has been fully defined and implemented. All fields, data types, and relationships from the ERD are in place. Ready for review.

**Comment by YampierFernandez** [comment]
Checked code for the model in “reviewEntityImplementation” branch, I approve this work for manager review.
