### ISSUE TITLE
[Lecture Topic Task] Documentation: Revamp Section 1 - Incorporating newer topics into the Informative Part

### ISSUE THREAD

**Issue by JadStelar** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#149]
Objective:

Incorporate the concept and usage of topics learned in class already present in the Milestone 2 Document such as domain engineering, requirements engineering, among others in section 1, "Informative Part".

Requirements:

- The "Informative Part" section must include clear and concise mentions of concepts taught in lecture in a way that is relevant to each subsection.
- Incorporated concepts, such as domain engineering, software design and requirements engineering, should be supported by references to class lectures or be relevant to the discussion had in the lecture and be present across relevant subsections.
- Ensuring the subsections have relevant mentions of these topics and their relation in the project, where applicable.

Completion Criteria:

The section 1 of the Milestone 2 Document has incorporated the topics learned in class in a manner that is relevant to the project and to the discussions had in class.

Time Constraint:

Completed by Friday, October 25, 2024.

Scoring:
Urgency: 6
Difficulty: 4

**Comment by JoshDG03** [comment]
Included the "Domain Engineering, Software Design, and Requirements Engineering" as section 1.3.3 and made changes to section 1.3.2

**Comment by CovasJJ** [comment]
Incorporated the lecture topics of "Domain Engineering, Software Design, and Requirements Engineering" in the goals in section 1.5 (Now 1.4)

**Comment by JadStelar** [comment]
Incorporated domain design, software design and requirements engineering into section 1.2 titled "Current Situation, Needs, and Ideas"
