### ISSUE TITLE
MainUser Class

### ISSUE THREAD

**Issue by DiegoVazquez1** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#15]
Objective: Create a MainUser class containing basic info. Full Name, Username, Email, Password, Phone. This will include at least 2 classes, SellerClass, BuyerClass (subject to change and additional classes). All the info will be store later in the database

Requirements:

1. Create constructor with all the info which will later be stored in the DB
2. Create getters to get all the info
3. Create subclasses Buyer and Seller

Completion Criteria:

1. Functional implementation of constructor
2. Verification of abstraction properties of Buyer/Seller to parent User class
3. Clearly defined Buyer/Seller classes
4. Functional implementation of getters
5. User input data can easily be stored in a list (later a database)

outcome: 
Users will be able to input their data and will be stored as User objects. If any info is needed it should be easily accessible through getters. 

Time Constraint:
- Done by the end of the sprint Monday September 9th

Difficulty: 7
Urgency: 6

**Comment by PerezMarcelo** [comment]
The **Seller** class extends User and adds shop-specific properties and methods. It includes a constructor for initializing personal and shop details and methods to get and set the shop name, address, and product list. The displayInfo() method shows all seller information, including shop details and products.

**Comment by PerezMarcelo** [comment]
The **Buyer** class extends User and adds buyer-specific features. It includes a constructor for personal details and methods for managing the shipping address and purchase history. The buy(item) method adds items to the purchase history, displayInfo() shows the buyer's details and purchase history, and json() provides a JSON representation of the data.
