### ISSUE TITLE
Documentation Lead Task - Monitor Milestone 2 Documentation Progress

### ISSUE THREAD

**Issue by NatiPerez459** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#151]
# Objective:
- Review completed assignments and overlook hybrid members activity throughout the Milestone ensuring all sections added to the Milestone 2 documentation are in order and follow all required guidelines.

# Requirements:
- Review completed assignments regarding the Milestone 2 documentation from team members to ensure they follow established requirements and guidelines.
- Review and understand Milestone 2 documentation guidelines provided by the professor.
- Maintain documentation of progress and missing requirements for the Milestone documentation.
- Ensure the Milestone documentation revisions follow the leyend format established on the guidelines.

# Completion Criteria:
- Milestone 2 documentation contains all sections provided on the guidelines.
- All completed assignments have been reviewed and tagged with Lead Reviewed labels.
- Revisions made follow the leyend established on the Milestone 2 guidelines.
- Milestone documentation adheres to a specific format.

# Time Constraint:
- End of Milestone 2: October 25, 2024

# Scoring:
- Urgency: ?
- Difficulty: ?

**Comment by Christian2101** [comment]
Verified the documentation, issues and completed assignments, made sure all of them followed the established requirements, format and guidelines, fixes were made to those that did not follow them.
