### ISSUE TITLE
Entity Relation Diagram Creation for Database Design

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#16]
Before the implementation of the database starts, we need to define and establish what data we want from the users. 

The task involves establishing the schema, tables, properties, and entity relations that will be used in the database. Implementation of the database is not required for this task. The end result of this task is to create and submit an Entity Relation Diagram that will be reviewed by the Team Leader and Managers, since the implementation of the database will be based around this initial design. The creation of this diagram will help facilitate documentation of the database's properties.

Scoring:
Difficulty: 3
Urgency: 8

Time Constraint:
Done by Wednesday September 4th

**Comment by JuanIranzo** [comment]
Here is the link to the LucidChart document where the Entity Relation Diagram was created. A PDF copy of the diagram will also be attached.

https://lucid.app/lucidchart/39131324-001a-433c-9380-a2516d52d408/edit?viewport_loc=-764%2C-240%2C2322%2C1589%2C0_0&invitationId=inv_f6e37857-114e-473e-a93f-58055fed6bd6 
[MercadoColegialERD.pdf](https://github.com/user-attachments/files/16857354/MercadoColegialERD.pdf)

**Comment by YampierFernandez** [comment]
This is the link for a new version of the diagram:
https://lucid.app/lucidchart/16f8266e-00f0-41be-b98d-71b2bf3522d0/edit?viewport_loc=-304%2C210%2C2808%2C1508%2C0_0&invitationId=inv_a0e86486-1798-4ec0-ac56-a2c2ffe4a8b1
