### ISSUE TITLE
[Lecture Topic Task] Sequence Diagram Creation

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#164]
Objective:

- Create several sequence diagrams for illustrating relation and interaction between system entities.

Requirements:

- Understand lecture provided in class titled "Sequence Diagrams".
- Generate 2 or more sequence diagrams that illustrate the ineraction between entities in different cases
- Integrate sequence diagrams to Milestone 2 documentation.

Completion Criteria:

- Completed section of sequence diagrams in Milestone 2 documentation.
- Created sequence diagrams for different scenarios that could happen
Time Constraint:

- October 25, 2024

Urgency and Difficulty

Urgency: 5
Difficulty: 4

**Comment by JuanIranzo** [comment]
Added one sequence diagram to the Milestone 2 documentation, under the section 3.1.1 titled Sequence Diagrams. The sequence diagram that I added details and illustrates a specific scenario, specified in the documentation.

**Comment by AlvinBadillo** [comment]
Added one sequence diagram to the Milestone 2 documentation in section 3.1.1 titled sequence diagrams. The diagram depicted describes the creation of a review, it is better detailed in the documentation.

**Comment by F3rnand0hr** [comment]
Added one sequence diagram to the Milestone 2 documentation, under the section 3.1.1 titled sequence diagrams. The diagram depicted describes how to searching works for the products.
