### ISSUE TITLE
Documentation: Revise 3.1 Concept Analysis

### ISSUE THREAD

**Issue by JadStelar** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#168]
Objective:

Review and edit section 3.1 titled "Concept Analysis" of the Milestone 2 documentation to apply the feedback given by the professor to clarify the process of identifying and naming common themes from user stories.

Requirements:

Carefully read and understand the professor's feedback regarding section 3.1.
Implement the professor's feedback and make all necessary revisions to the section.
Include clear examples on how user stories are used to derive and name concepts.

Completion Criteria:

Successfully revise section 3.1 to reflect the professor's feedback.
Concept Analysis contains how to derive the concept and what names to use, while removing mentions of the result into the terminology.
Use the correct format in the documentation to make the changes visible.

Time Constraint:

Completed by Friday, October 25, 2024.

Scoring:
Urgency: 5
Difficulty: 2

**Comment by CovasJJ** [comment]
Finished revising the last three concepts.

**Comment by JadStelar** [comment]
Revised Vendor, Market, and Product by establishing user stories that help conceptualize these concepts.
