### ISSUE TITLE
 Database Design: Users model backend connection

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#173]
Objective:
- Make the necessary connections for the users model to be accessed by the backend of the application as the items model is now.

Requirements:
- Create the necessary routes and connections for the users model

- Make sure the necessary functions can be performed on the users model within VScode using ThunderClient (get, post, etc.)

Completion Criteria:
- The data in users model can be safely and effectively accessed from the backend of the project.

- Submit modified code to GitHub on a separate branch.

- Post a screenshot on this issue page of a get all in the users model being performed in Thunder Client.

Time constraint:
- Saturday, November 2.

Scoring:
- Difficulty: 5
- Urgency: 7

**Comment by YampierFernandez** [comment]
![image_2024-11-02_194552959](https://github.com/user-attachments/assets/591c2c1e-0e33-45a2-9e70-fefb189a3f0c)

**Comment by YampierFernandez** [comment]
Changes were made are in the Users_model_connect branch.

**Comment by franRov** [comment]
Code behavior has been lead reviewed and merged successfully.
