### ISSUE TITLE
Team Lead Task - Monitor Backend Interface Team Performance

### ISSUE THREAD

**Issue by NatiPerez459** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#177]
# Objective:
-	 Communicate with the Backend Interface team, review completed assignments and overlook members’ activity throughout the Milestone maintaining documentation of accomplished activities guiding the team towards success.
# Requirements:
-	 Communicate with the Backend Interface team to establish sprint goals, discuss progress and ideas for future assignments.
-	 Review completed assignments from team members to ensure they follow established requirements and guidelines.
-	Review created code and ensured it complies with the requirements and passes test cases with the expected output.
-	Maintain documentation of progress and established individual goals for the Milestone.
# Completion Criteria:
-	Created record of held meeting recordings.
-	All completed assignments have been reviewed and tagged with Lead Reviewed labels.
-	Completed documentation of progress completed by individual team members and comparison of accomplishments with established team goals.
# Time Constraint:
-	End of Milestone 3: October 25, 2024
# Scoring:
-	Urgency: ?
-	Difficulty: ?

**Comment by PerezMarcelo** [comment]
https://docs.google.com/document/d/1AvkY4vtd5l6Q9Ro2CL5wK1G5GRR6bqf4P9OSNLfHvlw/edit?usp=sharing

**Comment by PerezMarcelo** [comment]
[Milestone 3.pdf](https://github.com/user-attachments/files/17941174/Milestone.3.pdf)
Milestone 3 Monitor Backend Interface Team Performance Documentation
