### ISSUE TITLE
Web UI Design 

### ISSUE THREAD

**Issue by yadzielperez09** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#18]
Requirements:

1.  Bring up ideas of design for UI of the web page of the Home Page.
2.  Bring up ideas of how things like the filters, prices, tags or categories will look in the description of articles in the home page.
3.  Bring up ideas of design for when a certain item is being selected/looked at.
4.  Decide which colors should be used for the web pages.

Completion criteria:

1.  Show a model of the UI design. 

Time constraint done by Wednesday, September 4, 2024

Difficulty: 3
Urgency: 4

**Comment by CdoxHype** [comment]
Here I attach the Users Welcome Page, Sellers and Clients Sing Up. We can implement also a button to Sing In in the Sign Up pages.
![Welcome-SingUp-page](https://github.com/user-attachments/assets/506eca50-525c-4d54-a5b1-2f262bf5f32c)

**Comment by david-baez-bravo** [comment]
[homepage_design.pdf](https://github.com/user-attachments/files/16882157/homepage_design.pdf)
Homepage design UI courtesy of Luis Hernández (CactusByte)

The task has been completed
