### ISSUE TITLE
[Lecture Topic Task] Documentation: Revise Section 2.1.4: Events, Actions and Behaviors

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#185]
### Objective:

- Revise the information in the Events, Actions and Behaviors section of the documentation.
- Integrate feedback from the professor for this section of the documentation

### Requirements:

- Comply with established guidelines
- Integrates professor's feedback
- Provide clearer examples for each of the points in this section
- Use appropriate terminology 
- Follow established format for changes

### Completion Criteria:

- Section 2.1.4 integrates feedback correctly
- Section 2.1.4 complies with pre-established guidelines, format, and terminologies

### Time Constraint:

Completed by: Tuesday, November 12
Urgency: 4
Difficulty: 6

**Comment by JuanIranzo** [comment]
Implemented feedback from Milestone 1 and 2 into the Events, Actions and Behaviors section of the documentation. Added a new action and corrected some behaviors.

**Comment by AlvinBadillo** [comment]
Implemented feedback from Milestone 1 and 2 into the Events, Actions, and Behaviors section of the documentation. Adjusted existing events, actions, and behaviors to align with the feedback from the professor.
