### ISSUE TITLE
Develoment and testing of basic HTML sign up with backend integration.

### ISSUE THREAD

**Issue by PerezMarcelo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#19]
**Objective:** 

- Create a basic HTML sign-up form with fields for username, email, and password. The form should send data to the backend code for processing.

**Requirements:**

- Create an HTML form with input fields for username, email, and password. Include a submit button to send the data to the backend.
- Ensure your backend code can receive POST requests from the form. The backend should process the received data. 
- Set up a testing environment where the HTML form can communicate with the backend, and you can observe the results.

**Completion Criteria:**

- The backend successfully receives the form data and processes it as expected.
- The HTML form submits data to the backend without errors.
- The backend sends an appropriate response back to the frontend after processing the form data.
- Ensure that all required fields are filled out and the data is in the correct format.
- The frontend and backend should communicate seamlessly, with no major issues during testing.

**Time Constraint:**

- Done by the end of the sprint Monday September 9th

**Difficulty:** 8
**Urgency:** 6

**Comment by JuanDelPueblo** [comment]
I added a basic backend using Node.js and Express.js which receives a POST request from the client web page. It then relays the received JSON back to the client along with a login confirmation message. To make sure it works, I added a fetch call to the submit button on the client web page. This will send the POST request to the server, once it replies it will create a paragraph element with the received message at the end.

To test this backend:
1. Install Node.js v20 from https://nodejs.org/en/download/package-manager
2. Go to the server directory on the terminal (e.g. `cd server` from the project root)
3. Run the command `npm install` to install all dependencies needed
4. Run the command `npm run start` to launch the server
5. Open the `index.html` file in the client folder using your browser of choice.
6. Fill out the form then press submit.

**Comment by FabiolaZTorres** [comment]
I implemented logic to ensure that users could only sign up if they had filled every field within the form. If a user tries to submit an incomplete form, an error message would prompt them to complete all fields. This message will disappear once all fields are completed, and the form submitted.
