### ISSUE TITLE
Email Confirmation Database Connection

### ISSUE THREAD

**Issue by jonael-garcia26** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#190]
Objective:

Complete the implementation of the email confirmation feature.

Requirements:

Database Integration:

Connect the email confirmation feature with the users' database.

Completion Criteria:

After a user is created, the email confirmation feature sends an email from the official Gmail account of the app.

Pending:

- Implement logic for users to confirm their accounts by clicking the link.
- Update the user status to confirmed in the database after successful confirmation.

Time Constraint:

Deadline: Tuesday, October 12
Scoring:

Urgency: 6/10
Difficulty: 7/10

**Comment by jonael-garcia26** [comment]
![image_2024-11-12_002749633](https://github.com/user-attachments/assets/5986a0b6-75dd-4e6c-a6c7-3c85b7fbf571)

Luego de tomar la foto le cambie algunas cosas con el formato del email, puede ser cambiado luego nuevamente

**Comment by YampierFernandez** [comment]
Checked code on email-confirmation. Approve work for manager review.
