### ISSUE TITLE
Database Design: Order model backend connection

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#194]
## Objective:
•	Make the necessary connections for the order model to be accessed by the backend of the application as the items model is now.

## Requirements:
•	Create the necessary routes and connections for the order model
•	Make sure the necessary functions can be performed on the order model within VScode using ThunderClient (get, post, etc.)

## Completion Criteria:
•	The data in order model can be safely and effectively accessed from the backend of the project.
•	Submit modified code to GitHub on a separate branch.
•	Post a screenshot on this issue page of a get all or a post in the order model being performed in Thunder Client.

## Time constraint:
•	Tuesday, November 12.

## Scoring:
•	Difficulty: 4
•	Urgency: 9

**Comment by Cabinetman** [comment]
![Screenshot 2024-11-12 034515](https://github.com/user-attachments/assets/74209fa9-5b8a-4ffb-a384-ef47ea629a5f)
Connected the Order model to the backend and thunder client test worked as intended. I did the implementation on the [sell_model_implementation](https://github.com/uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online/tree/sell_model_implementation).

**Comment by franRov** [comment]
This issue has been lead reviewed, pushed to Database branch.
