### ISSUE TITLE
Database Design: Sell model backend connection

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#196]
## Objective:
•	Make the necessary connections for the sell model to be accessed by the backend of the application as the items model is now.

## Requirements:
•	Create the necessary routes and connections for the sell model
•	Make sure the necessary functions can be performed on the sell model within VScode using ThunderClient (get, post, etc.)

## Completion Criteria:
•	The data in sell model can be safely and effectively accessed from the backend of the project.
•	Submit modified code to GitHub on a separate branch.
•	Post a screenshot on this issue page of a get all or a post in the sell model being performed in Thunder Client.

## Time constraint:
•	Tuesday, November 12.

## Scoring:
•	Difficulty: 4
•	Urgency: 9

**Comment by AlvinBadillo** [comment]
![image](https://github.com/user-attachments/assets/a512b9fa-eb07-4f35-a5eb-c14d37eef900)
The sell model integration with the backend is complete. Routes (POST, GET, PUT, DELETE) are functional and tested via Thunder Client. Code has been pushed to unit_testing_models branch. Screenshot attached.

**Comment by YampierFernandez** [comment]
Sell route checked in unit_testing_models branch. Work approved for manager review.
