### ISSUE TITLE
Welcome Page Redesign Implementation

### ISSUE THREAD

**Issue by RyanVelez101** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#200]
Objective:

Implement the UI redesign of the Welcome Page.

Requirements:

Implement the new design for the Welcome Page that the team had previously designed in figma. 

Completion Criteria:

The Welcome Page redesign has been implemented correctly with previous functions intact. 

Time constraint:
Complete by Tuesday, November 12th, 2024.

Difficulty Score:
7
Urgency Score:
8

**Comment by CactusByte** [comment]
WebsiteEnhancement
![ss2](https://github.com/user-attachments/assets/ef7ce3b6-5dcb-4139-9a9a-102e4a283bba)
