### ISSUE TITLE
[Lecture Topic Task] Add section 2.1.6: Stakeholder Information

### ISSUE THREAD

**Issue by JuanDelPueblo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#216]
**Objective:**  
Describe the needs of the primary, secondary, and tertiary stakeholders and how they impact the project's outcome.

**Requirements:** 
- Define who are the stakeholders and document each stakeholder’s specific requirements and expectations.  
- Ensure alignment with project goals and feature implementations.  
- Format the section by tier for easy readability.

**Completion Criteria:**  
- Comprehensive stakeholder documentation finalized and approved.  
- All stakeholder requirements clearly defined and structured.  
- Section reviewed for consistency and clarity.

**Time Constraint:**  
Completion by Wednesday, November 27th, 2024.

**Difficulty:** 7
**Urgency:** 4

**Comment by JuanDelPueblo** [comment]
I have completed my share of the work for this task, focusing on the primary stakeholders.

**Comment by CovasJJ** [comment]
I have completed my part of this task. I worked on the secondary stakeholders.

**Comment by gcal77** [comment]
Added the tertiary stakeholders.
