### ISSUE TITLE
[Lecture Topic Task] Add section 2.1.7: Business Processes

### ISSUE THREAD

**Issue by JuanDelPueblo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#217]
**Objective:**  
Document key business processes relevant to the domain, capturing long-winded behaviors and workflows regularly performed by stakeholders.

**Requirements:** 
- Research and identify critical business processes within the system's domain, focusing on strategic, tactical, and operational management aspects.
- Break down processes into workflows that include: Input, Process Steps, Output
- Ensure coverage of multiple categories, such as workflow management, decision-making, and R&D.
- Provide examples of processes for key stakeholders.
- Use clear and concise language and structuring.

**Completion Criteria:**  
- Business processes are documented for at least three primary stakeholders.
- Each documented process includes Input, Process Steps, and Output.
- At least one process is detailed for strategic, tactical, and operational domains.
- Examples provided align with the software system's purpose and objectives.

**Time Constraint:**  
Completion by Wednesday, November 27th, 2024.

**Difficulty:** 7
**Urgency:** 6

**Comment by JuanDelPueblo** [comment]
I have completed my share of the work for this task, focusing on the business processes for the primary stakeholder.

**Comment by gcal77** [comment]
Added the business processes for the secondary stakeholders.
