### ISSUE TITLE
[Lecture Topic Task] Add section 2.1.8: Domain Facets

### ISSUE THREAD

**Issue by JuanDelPueblo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#218]
**Objective:**  
Analyze and document the key domain facets relevant to the software project.

**Requirements:** 
- Document core domain facets: generic perspective, intrinsics, business procedures, support technology, and rules and regulations.
- Base the analysis and descriptions on hypothetical scenarios, predefined materials, and academic references.
- Provide clear, structured documentation with examples for clarity and alignment with the domain model.

**Completion Criteria:**  
- The domain facets section includes detailed descriptions of all required facets.
- Each facet is validated for consistency and relevance through the stakeholder's perspective.
- Documentation provides examples for clarity.

**Time Constraint:**  
Completion by Wednesday, November 27th, 2024.

**Difficulty:** 5
**Urgency:** 6

**Comment by JuanDelPueblo** [comment]
I have completed my share of the work for this task, writing about the generic perspective, business procedures, and instrinsics facets.

**Comment by DiegoVazquez1** [comment]
I have completed the Rules and regulations, scripts and human behavior .
