### ISSUE TITLE
[Lecture Topic Task] Fault Analysis and Documentation

### ISSUE THREAD

**Issue by Kaariinaa08** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#220]
Objective:
Identify potential faults in the Mercado Colegial platform, analyze their causes and effects, and propose mitigation strategies. Use concepts from the "Fault Analysis" topic in the "Requirements Engineering & Requirements Facets" lecture to guide the analysis.

Requirements:
1. Failure Mode Identification: Identify key failure modes that could disrupt the platform. Categorize failures based on their impact on system components and user experience.
2. Failure Mode Effect Analysis (FMEA): Analyze the effects of each identified failure mode on system operations.
Assess severity (S), likelihood (L), and detectability (D) for each failure mode. Calculate Risk Priority Numbers (RPN) to prioritize mitigation efforts.
3. Fault Tree Analysis (FTA): Construct a hierarchical fault tree for one or more critical faults.
Trace intermediate faults and root causes using a structured fault tree diagram.
4. Mitigation Strategies: Propose solutions to prevent, detect, or mitigate high-priority faults. Address both technical measures (e.g., redundancy systems, real-time monitoring) and process-oriented solutions.

Completion Criteria:
1. Fault List: Provide a categorized list of faults, their potential causes, and their effects on system reliability.
2. FMEA Table: Include a detailed table with severity, likelihood, detectability, and RPN values for all identified failure modes.
3. Fault Tree Diagram: Present at least one fault tree diagram illustrating the root causes and propagation of a critical fault.
4. Mitigation Report: Summarize proposed solutions and explain how they address high-priority faults.

Documentation:
The fault analysis findings will be documented in Section 3.5: Fault Analysis as part of the Analytic Part.

Time Constraint:
Sunday, November 24

Scoring:
Urgency: 4
Difficulty: 7

**Comment by Kaariinaa08** [comment]
Log:
(3.5) Created Section 3.5: Fault Analysis, detailed different fault types and their possible impacts, identifying potential faults in the Mercado Colegial platform, analyzing their causes and effects, and proposing mitigation strategies.

**Comment by Kaariinaa08** [comment]
Log:
(3.5) Created Section 3.5: Fault Analysis, detailed different fault types and their possible impacts, identifying potential faults in the Mercado Colegial platform, analyzing their causes and effects, and proposing mitigation strategies.

**Comment by JuanIranzo** [comment]
Log:
(3.5) Created sub-section 3.5.1 (Fault List), listing and detailing different types of faults and examples
