### ISSUE TITLE
[Lecture Topic Task] Domain Engineering and Software Design in Milestone 3 Documentation

### ISSUE THREAD

**Issue by elliot-gomez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#221]
Objective: Update the Milestone 3 documentation to incorporate domain engineering and software design principles learned in class. Address feedback from Milestone 2 and ensure alignment with the clarified domain model.

Requirements:
- Align domain description with clarified scope.
- Adjust components for consistency.
- Address all milestone 2 comments.
- Relocate “Scope, Span, Synopsis” section.

Completion Criteria:
- Domain description and facets are updated, detailed, and relevant.  
- The software design section reflects revised and validated components.  
- All milestone 2 feedback is addressed. 

Time Constraint: Complete by Wednesday, November 27, 2024

Difficulty Score: 7
Urgency Score: 6

**Comment by JuanIranzo** [comment]
Relocated Software Design, requirements engineering, and  domain engineering withing the Scope, Span and Synopsis section of the documentation as requested by the professor's feedback. Eliminated redundancies within this same section as pointed out by the professor. Added new bullet point in Synopsis section to ensure smoother information flow within the documentation

**Comment by JadStelar** [comment]
Ensured that domain description aligned with identified scope. Added description of revised and validated components into the software design part.

**Comment by elliot-gomez** [comment]
I revised and ensured the domain engineering and design sections reflect Milestone 2 feedback accurately. Also, I helped adjust terminology and streamline redundant elements across sections.
