### ISSUE TITLE
[Lecture Topic Task] Rules and Regulations in Milestone 3 Documentation

### ISSUE THREAD

**Issue by elliot-gomez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#222]
Objective: Refine and document rules and regulations in Milestone 3, ensuring they align with system constraints and address Milestone 2 feedback.

Requirements:
- Define clear and actionable rules and regulations for system operation (e.g., compliance standards, access control, data handling).
- Ensure regulations address shared system phenomena and align with domain requirements.
- Use precise, enforceable language, incorporating “must” or “shall” phrasing.

Completion Criteria:
- Rules and regulations are incorporated into the documentation.
- All feedback from Milestone 2 is incorporated and resolved.

Time Constraint: Complete by Wednesday, November 27, 2024

Difficulty Score: 7
Urgency Score: 6

**Comment by CovasJJ** [comment]
I successfully did my part working in Section **1.5 Rules and Regulation** in the documentation.

**Comment by PerezMarcelo** [comment]
Information added covers the project's rules and regulations.
