### ISSUE TITLE
[Lecture Topic Task] Phenomena in Milestone 3 Documentation

### ISSUE THREAD

**Issue by elliot-gomez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#223]
Objective: Enhance the documentation of phenomena in Milestone 3 by identifying and describing domain phenomena relevant to system requirements. Incorporate Milestone 2 feedback and align with lecture concepts.

Requirements: 
- Identify and define domain phenomena related to the project scope (e.g., user roles, resource ownership, transactions).
- Ensure phenomena are linked to the requirements they inform.
- Integrate and address all relevant feedback from Milestone 2.

Completion Criteria:
- Phenomena are well-documented and directly linked to domain requirements.
- Terminology is clear, concise, and consistent across the document.
- Feedback from Milestone 2 has been resolved and incorporated.

Time Constraint: Complete by Wednesday, November 27, 2024

Difficulty Score: 8
Urgency Score: 6

**Comment by PerezMarcelo** [comment]
Added information linking domain phenomena to project requirements. Feedback from Milestone 2 has been fully addressed and incorporated.

**Comment by CovasJJ** [comment]
After reviewing the information, I believe the task has met its Completion Criteria.
