### ISSUE TITLE
[Lecture Topic Task] Create Unit Tests Registration and Login Pages

### ISSUE THREAD

**Issue by FabiolaZTorres** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#227]
**Objective:**
Develop unit tests for the login and registration pages to ensure the input data entered by users is stored properly in the database and verify that all validation rules for the input are correctly enforced.

**Requirements:**
Create test cases for the following scenarios:

- Registration: 
    - Ensure that the user input is successfully saved in the database after registration.
    - Validate that password hashing is applied correctly before saving.
    - Check if database prevents duplicate user registrations.
- Login:
    - Verify that the login authenticates a user only if the entered credentials match the stored data.
    - Confirm that incorrect credentials produce the appropriate error messages.
- Implement tests for edge cases like empty fields, special characters, invalid formats, etc.

**Completion Criteria:**

- Unit tests are implemented for all scenarios described in the Requirements section.
- All tests pass successfully.

Urgency: 6
Difficulty: 7

**Comment by jonael-garcia26** [comment]
![image_2024-11-25_171949550](https://github.com/user-attachments/assets/e3252a75-e7c4-401e-9772-b290145b7ac8)


I created the tests for the LOGIN functions; 3 out of 4 tests pass, except for the first one, which is supposed to test a successful login. The theory is that the error lies in the logic for adding the user to the database.

**Comment by FabiolaZTorres** [comment]
![Results registrationInputValidation](https://github.com/user-attachments/assets/d5452a17-5c07-4a43-a2e1-1813ef05e8e5)
The test validates that user input on the registration form is properly saved in the database. At the time this test was run, the test failed due to a bug where the name and role of the user were missing or incorrectly stored from the database. This led to a mismatch with the input and database information.

----
![Resuslts duplicateAccountValidation](https://github.com/user-attachments/assets/dce1edd7-6d86-4710-9e76-6025e0b41ec9)
The test validates that accounts created with emails that are attached to preexisting accounts cannot be created. It passes.

**Comment by PerezMarcelo** [comment]
<img width="1116" alt="Screenshot 2024-11-27 at 11 31 22" src="https://github.com/user-attachments/assets/9b2fe4c1-2795-43f5-81c8-da2ece3b141d">
Testing login edge cases

**Comment by PerezMarcelo** [comment]
<img width="1126" alt="Screenshot 2024-11-27 at 11 51 38" src="https://github.com/user-attachments/assets/0e0026b3-5dd4-4a10-b22e-cdebd6b55e67">
Test results for Registration edge cases.
