### ISSUE TITLE
Database design: Refactor sell controller to match other controllers

### ISSUE THREAD

**Issue by AlvinBadillo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#229]
Objective:
- Refactor the sell controller to align with the structure and functionality of other controllers in the application.

Requirements:
- Review the implementation of existing controllers (e.g., items or other relevant controllers) to ensure consistency.
- Update the sell controller to match coding patterns, structure, and functionality.

Completion Criteria:
- The sell controller follows the same structure and conventions as the other controllers in the application.

Time Constraint:
- Friday, November 15.

Scoring:
- Difficulty: 5
- Urgency: 9

**Comment by AlvinBadillo** [comment]
Completed the refactoring of the delete and update functionalities for the sell controller. Both have been updated to align with the structure, conventions, and functionality of other controllers in the application.

**Comment by JuanIranzo** [comment]
Implemented the rest of the CRUD functionalities of the Sell controller. Design aligns with other controller implementations

**Comment by YampierFernandez** [comment]
Checked sell controller in sellControllerRedesign branch. Work approved for manager review.
