### ISSUE TITLE
Product Listing Page Design

### ISSUE THREAD

**Issue by Kaariinaa08** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#23]
Objective: Create a basic design for the Product Listing Page that allows users to easily browse and filter products.

Requirements:
- Generate design ideas for the layout of the Product Listing Page.
- Develop concepts for filters and sorting options.
- Design how the product grid/list will look, including images, names, and prices.
- Choose colors that will align with the existing web page.

Completion Criteria:
Present a model of the Product Listing Page design.

Time Constraint:
Complete by Friday, September 6th, 2024.

Difficulty Score: 4

Urgency Score: 3

**Comment by Kaariinaa08** [comment]
![Rough Draft Of Listing Page #1](https://github.com/user-attachments/assets/57ac3836-fd91-4531-8cb6-fa1ed97524eb)

**Comment by david-baez-bravo** [comment]
Karina Lopez is adding some additional stuff, label will go back to in progress.

**Comment by Kaariinaa08** [comment]
![Draft #2](https://github.com/user-attachments/assets/db550af1-3895-49b5-9d00-d543d13f3696)
