### ISSUE TITLE
[Lecture Topic Task] Unit Test for Database Model: Sell Model - CREATE Functionality 

### ISSUE THREAD

**Issue by AlvinBadillo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#230]
Objective:
- Create a unit test for the create functionality of the Sell model. The test will ensure that a Sell document can be successfully created in the database, adhering to all model validations and requirements.

Requirements:
- Write Create Operation Test for the Sell Model:
- Test that a Sell record is successfully created when all required fields (user_id, item_id, price) and optional fields (quantity, date_listed) are provided with valid data.

Validation Testing:
- Ensure the user_id and item_id are required and reference existing records.
- Confirm that the price field is required and must be a valid number.
- Test default values for optional fields (quantity defaults to 1, date_listed defaults to the current date).

Error Handling:
- Test behavior when required fields are missing (e.g., user_id, item_id, or price).
- Test behavior with invalid data types (e.g., non-numeric price or invalid IDs for user_id and item_id).
Completion Criteria:
A unit test script that:
- Covers typical creation scenarios and edge cases.
- Includes assertions to validate success and failure scenarios.
- Confirmation that the create operation behaves as expected:
- Valid Sell records are stored in the database.
- Invalid inputs throw appropriate errors.

Time Constraint
Tuesday, November 26

Scoring
Urgency: 5
Difficulty: 4

**Comment by AlvinBadillo** [comment]
![image](https://github.com/user-attachments/assets/31a8d7a5-9746-4210-8b78-8b18a67858be)
I have created a unit test for the create functionality of the sell controller. The test validates that a sell entry is successfully created when provided with a valid user and item.

**Comment by YampierFernandez** [comment]
Work checked and approved for manager review.

**Comment by JoshDG03** [comment]
![invalid user unit test](https://github.com/user-attachments/assets/7ccbe551-b843-4905-9abe-e63d9aa1ac0c)
I created a unit test for the create functionality of the sell controller. The test makes sure that a sell cannot be created with an invalid user ID.

**Comment by YampierFernandez** [comment]
Work checked and approved for manager review.
