### ISSUE TITLE
[Lecture Topic Task] Unit Test for Database Model: Sell Model - DELETE Functionality

### ISSUE THREAD

**Issue by AlvinBadillo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#231]
Objective:
- Create a unit test for the delete functionality of the Sell model. The test will ensure that a Sell record can be successfully deleted from the database and handle scenarios where the record does not exist.

Requirements:
- Write Delete Operation Test for the Sell Model
- Test that a Sell record can be deleted successfully when it exists in the database.
- Verify that the record is removed from the database and cannot be found afterward.

Validation Testing:
- Confirm that attempting to delete a Sell record using an invalid or malformed ID results in an appropriate error.
- Test that attempting to delete a non-existent Sell record (valid but non-existent ID) does not break the application but handles the error gracefully.

Completion Criteria:
A unit test script that:
- Covers successful and unsuccessful delete scenarios.
- Includes assertions to validate success and failure cases.
- Confirmation that the delete operation behaves as expected:
- The Sell record is removed from the database when it exists.
- Errors are properly handled when the record does not exist or the ID is invalid.

Time Constraint:
Tuesday, November 26

Scoring
Urgency: 5
Difficulty: 4

**Comment by AlvinBadillo** [comment]
![image](https://github.com/user-attachments/assets/f8bf0cd2-7d40-48cb-92ff-e4998c42d1c0)
I have created a unit test for the delete functionality of the sell controller. The test ensures that a sell entry is successfully deleted when a valid sell ID is provided.

**Comment by YampierFernandez** [comment]
Work checked and approved for manager review.

**Comment by JoshDG03** [comment]
![handle deletion unit test](https://github.com/user-attachments/assets/e1d5b321-6ed1-47d9-8a44-9aa55e1522d2)
I created a unit test for the delete functionality of the sell controller. The test handles the deletion of a non-existent sell when an Invalid ID is provided.

**Comment by YampierFernandez** [comment]
Work checked and approved for manager review.
