### ISSUE TITLE
Enhance User Validation in the Sell Schema

### ISSUE THREAD

**Issue by JoshDG03** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#232]
Objective: Improve data integrity in the Sell model by ensuring that the user_id field references an existing User document in the database.

Requirements:

- Update the Sell schema to include a custom validator for the user_id field.

- Implement asynchronous validation to check the existence of the referenced User document before saving a Sell document.

- Add a meaningful error message, such as "User not found," which will be thrown if the validation fails.

Expected Outcome:

- The Sell schema should prevent the creation of any Sell documents where the user_id does not correspond to a valid, existing User document.Proper error handling should be in place to manage and return validation errors effectively.

Assessment Criteria:

- Correct implementation of the asynchronous validator within the user_id field.

- Successful execution of unit tests that verify the functionality of the validator.

- Code clarity and adherence to the project’s coding standards.

Urgency: 10
Difficulty: 4

**Comment by JoshDG03** [comment]
The Sell schema was updated to include a custom asynchronous validator for the user_id field. This validator uses the countDocuments() method to check the presence of the user in the database. A specific error message, "User not found", was configured to be thrown if the validation fails, indicating the non-existence of the referenced user. This was developed in the unit_testing_models branch.

**Comment by YampierFernandez** [comment]
Work checked and approved for manager review.
