### ISSUE TITLE
Tech Stack Documentation

### ISSUE THREAD

**Issue by JadStelar** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#24]
Objective: Create documentation for the tech stack used in the project that allows for seamless collaboration between teams.

Requirements:

- Create documentation of detailed and specific information of used technologies, libraries, programming languages by each team.
- Information on how to set up the environment, deploy code for review, and troubleshoot common issues.

Completion Criteria:

- Contains a detailed report on all the technologies used by each team and common information of the environment.

Time Constraint:

- Complete by Friday, September 6th, 2024.

Difficulty Score: 3

Urgency Score: 5

**Comment by JadStelar** [comment]
https://docs.google.com/document/d/1Bg0lHtuzFIWX4ny9sntZGf4Mncs9wMP5t9Bogsy2hkQ/edit?usp=sharing

**Comment by ActuallySeb** [comment]
Everything in the document seems to be in line with what the others are using. Good job.
