### ISSUE TITLE
Web Schema Connections

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#25]
Objective: Create a skeleton where you can see how each page will connect to the other and the content of each one. This will result in a more organized and visually-friendly design development.

Requirements:

- Mention the different pages that users may interact with (home page, buyer sign up page, seller sign up page)
- Organize them neatly with clear lines as to how pages connect

Completion Criteria:

- A diagram with all the pages the Web Dev team will be working on and how these pages interact with eachother

Time Constraint:

- Complete by Thursday, September 5th, 2024.

Difficulty Score: 2

Urgency Score: 6

**Comment by NatiPerez459** [comment]
There already exists tasks for the UI design for the product listing and home page, aswell as another task for the tech stack that will cover the technologies used for each group. You could select more specific objectives like the documentation of how each page will relate to one another with mock designs for pages that have not been stated like the registrations, etc. Make sure to specify excatly what will be delivered to meet the completion criteria whether it is documentation for xy or mock designs for xy.

**Comment by CdoxHype** [comment]
Here I attach the visual Web Schema.
[Diagram.pdf](https://github.com/user-attachments/files/16909545/Diagram.pdf)
