### ISSUE TITLE
Merge Conflict Resolution

### ISSUE THREAD

**Issue by ActuallySeb** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#29]
Objective: Resolve conflicts when merging any branches as they arise. 

Completion Criteria: Ensure that all merges go as smoothly as possible

Completion Date: End of 1st Milestone

Urgency: 7
Difficulty: 6

**Comment by david-baez-bravo** [comment]
This task format will no longer be used. Merge conflict tasks will be created and solved as they arise.
