### ISSUE TITLE
Define Documentation Guidelines and Create an Initial README File

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#30]
Objective: A README file is essential for the project's success, progress tracking, and evaluation. Therefore, we need to create an official README file structure that follows existing documentation standards and provides clear instructions on adhering to the chosen documentation guidelines.

Requirements:  
- Research existing README formats and select the one most suited for the project's needs.  
- Design an appropriate structure for an initial README file and implement the selected format.
- Create a section within the README file that provides instructions on how to follow the established documentation guidelines.

Subtasks:  
- [x] Researching and selecting a suitable README format (Markdown, org-mode, etc.) – Elliot Gomez  
- [x] Initial README Creation – CactusByte  
- [x] Content Guidelines and Instruction Writing – gcal77

Completion Criteria:  
- Creation of a README file that complies with the chosen documentation format, complete with structure and guidelines for documentation.

Time Constraint:  
- Completed and shared by Sunday, September 8th.

Scoring:  
- Urgency: 6  
- Difficulty: 6

**Comment by elliot-gomez** [comment]
Aquí les dejo el PDF de la investigación que hice sobre qué formato de documentación debemos usar y las pautas generales que se deben seguir al crear el documento y las instrucciones para ello: 
[Suitable Documentation Format Research.pdf](https://github.com/user-attachments/files/16947416/Suitable.Documentation.Format.Research.pdf)

**Comment by gcal77** [comment]
I'm attaching the instructions for the documentation format guidelines. When the actual template is created then I will add these instructions to it.
[Markdown Content Guidelines and Instruction Writing.pdf](https://github.com/user-attachments/files/16989772/Markdown.Content.Guidelines.and.Instruction.Writing.pdf)

**Comment by david-baez-bravo** [comment]
The read me file created can be found in the web dev branch.
