### ISSUE TITLE
Cybersecurity Protocols

### ISSUE THREAD

**Issue by F3rnand0hr** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#32]
After completion of features like signing up or logging in, the security of our users is going to be one of our main goals.

Objective: Research about the main cybersecurity protocols, and methods to make our users be and feel safe. The only goal here is to familiarize ourselves with these principles so we can start having an idea on how we will implement them into our website. 

Requirements:
- Find sources, videos on how to implement cybersecurity principles into the website.

Completion Criteria
- A document or list of sources containing important cybersecurity practices.

Time Constraint: 
- Monday September 23rd

Difficulty: 4
Urgency: 3

**Comment by PerezMarcelo** [comment]
[Cybersecurity Principles for secure website.pdf](https://github.com/user-attachments/files/16924388/Cybersecurity.Principles.for.secure.website.pdf)
