### ISSUE TITLE
Database Desing: Research language for development

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#33]
Objective: Investigate and ultimately choose a programming language to use for the backend. 

Requirements:  
- Propose a programing language or multiple and provide some reasons as to why the subject language would be a good fit for use. 

Completion Criteria: 
- This issue is considered complete once the members have chosen the language to be used. 

Time Constraint: Friday, September 6th

Urgency: 5
Difficulty: 2

**Comment by Cabinetman** [comment]
I would recommend using JavaScript (Node.js) for the backend. Node.js is well-supported in VS Code, which comes with built-in JavaScript IntelliSense, debugging, and formatting features. Additionally, Node.js is compatible with MongoDB so no problems there.

**Comment by YampierFernandez** [comment]
Read and approved
