### ISSUE TITLE
Database Design: Resources for learning 

### ISSUE THREAD

**Issue by YampierFernandez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#36]
Objective: Provide learning tools like links to helpful websites or videos that help the developers learn more about how they can implement the database.  

Requirements: 
- Provide links to websites, videos or documentation.
- Write a short description of the content their links offer. The links must lead to content that is informative and trustworthy for the developers.
- At least one source on databases for products/online selling.

Completion Criteria: 
- 3-4 links on the topic.

Time Constraint: Saturday, September 7th

Urgency: 6
Difficulty: 3

**Comment by JuanIranzo** [comment]
Attached is a link to a google doc that summarizes the process of developing and implementing a database using Javascript in MongoDB, which is the database management system that we will be using. I also include the link to the tutorial video. If anyone has trouble accessing the document, please let me know. 

https://docs.google.com/document/d/1VXpQNsh3FZcBAUNzz3Eyro0_R7PrThGxKG3ARacxcyI/edit?usp=sharing 
https://www.youtube.com/watch?v=dCWFLN1i9Ss

**Comment by ActuallySeb** [comment]
Attached are more resources for learning about databases:

Introductory video to databases:
https://www.youtube.com/watch?v=wR0jg0eQsZA

Thread touching on databases used by retailers and the best use case of for relational and non-relational databases:
https://www.quora.com/What-kind-of-databases-are-typically-used-by-large-scale-online-retail-stores-to-store-customer-data#:~:text=Large-scale%20online%20retail%20stores%20typically%20use%20relational%20databases%2C%20such,handle%20large%20amounts%20of%20data.

Video discussing differences between relational and non-relational databases:
https://www.youtube.com/watch?v=Q5aTUc7c4jg&t=36s

Official Documentation for MongoDB:
https://www.mongodb.com/docs/

**Comment by YampierFernandez** [comment]
Read and approved
