### ISSUE TITLE
Research on Lazy Loading Images for Faster Page Load Times

### ISSUE THREAD

**Issue by gcal77** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#39]
**Objective:** Research techniques for lazy loading images to improve page performance, particularly for product listing pages with many images. 

**Requirements:**
- Find resources or tutorials on implementing lazy loading of images.
- Summarize key points and methods for implementing this feature.

**Completion Criteria:**
- A document with recommendations for lazy loading, including links to useful resources.

**Time Constraint:**
- Done by Tuesday, September 10th, 2024.

Difficulty: 3
Urgency: 3

**Comment by PerezMarcelo** [comment]
[Lazy Loading Images.pdf](https://github.com/user-attachments/files/16935104/Lazy.Loading.Images.pdf)
All information on lazy loading require to implement it on our project.
