### ISSUE TITLE
Implement Basic Error Pages (404, 500)

### ISSUE THREAD

**Issue by gcal77** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#40]
**Objective:** Create basic error pages for common HTTP errors like 404 (Page Not Found) and 500 (Server Error). 

**Requirements:**
- Design user-friendly error pages that match the site’s overall design.
- Ensure the 404 page suggests navigation options to return to the main sections of the site.
- Ensure the 500 page informs users of potential server issues and suggests trying again later.

**Completion Criteria:**
- Functional 404 and 500 error pages are displayed when respective errors occur.

**Time Constraint:**
- Done by Friday, September 13th, 2024.

Difficulty: 4
Urgency: 4

**Comment by F3rnand0hr** [comment]
[
![404 not found](https://github.com/user-attachments/assets/92f749b5-79b6-4331-a33f-a061cd703f6f)
![Internal Server Error](https://github.com/user-attachments/assets/b8b58260-645c-469e-9404-a16027fbb3d1)
](url)
