### ISSUE TITLE
MongoDB Environment Setup

### ISSUE THREAD

**Issue by JadStelar** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#47]
Objective: Add MongoDB as a Dependency to the project and connect the MongoDB Atlas account to the project.

Requirements:

- MongoDB dependencies are installed for the Node.js server.
- The MongoDB Atlas account is connected to the project.
- Ensure the installation and connection are properly setup.

Subtasks:

- [x] Install MongoDB as a dependency for the Node.js server.
- [x] Connecting the MongoDB Atlas account to the project.

Completion Criteria:

The successful installation of the MongoDB dependencies and successful connection to the MongoDB Atlas account.

Time Constraint:

Completed by Wednesday, September 11th

Scoring:
Urgency: 3
Difficulty: 4

**Comment by ActuallySeb** [comment]
The script successfully connects and retrieves data from the MongoDB database
