### ISSUE TITLE
Welcome Page Code UI

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#49]
Requirements:
Create UI code for welcome page based on mock sketches already designed using Vue. It should have the design already discussed and follow the harmony of all the pages. It should contain the two "Client" or "Seller" buttons that were discussed in the design. It is not a requirement for this delivery that the buttons have functionality, but they must be prepared to have it. Follow the feed by Julio Camacho.

Completion Criteria:
Submit a page with all the requirements mentioned. Push a file containing the coded page to the web UI branch. User is able to view the UI of the welcome page.

Time Constraint:
 
    Complete by Friday, September 13th, 2024.
 
Difficulty Score: 4
 
Urgency Score: 4

**Comment by NatiPerez459** [comment]
![image](https://github.com/user-attachments/assets/c966c84e-eebd-41ef-95b7-edbf26c274d2)
