### ISSUE TITLE
Client Registration/Login Page Code UI

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#50]
Objective: Create the client registration and log in page for the website

Requirements:
You should keep the design already discussed. This page should have two sections, one where the customer can register and another where they can log in if they already have an account. All of this should be possible on the same page. It should have the respective buttons. It is not a requirement for this delivery that the buttons have functionality, but they must be prepared to have it.
Follow the feed by Julio Camacho.

Completion Criteria:
Submit a page with all the requirements mentioned. Push a file containing the coded page to the web UI branch.

Time Constraint:
 
    Complete by Friday, September 13th, 2024.
 
Difficulty Score: 4
 
Urgency Score: 6

**Comment by NatiPerez459** [comment]
![image](https://github.com/user-attachments/assets/54bec915-dbc5-450b-b9ba-f2d09e52b779)
