### ISSUE TITLE
Seller Registration/Login Page Code UI

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#51]
Requirements:
You should keep the design already discussed. This page should have two sections, one where the Seller can register and another where they can log in if they already have an account. All of this should be possible on the same page. It should have the respective buttons. It is not a requirement for this delivery that the buttons have functionality, but they must be prepared to have it. Follow the feed by Julio Camacho.

Completion Criteria:
Submit a page with all the requirements mentioned. Push a file containing the coded page to the web UI branch.
Time Constraint:
 
    Complete by September 18th, 2024.
 
Difficulty Score: 3
 
Urgency Score: 6

**Comment by NatiPerez459** [comment]
![image](https://github.com/user-attachments/assets/a9263019-95aa-46b2-8ff6-f7c3cc4f9b97)
