### ISSUE TITLE
Home Page Code UI

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#52]
Requirements:
Create UI code for home page previoulsy designed in mock sketches using Vue. It should keep the design already discussed, even if adjustments can be made in the future. It should have the following buttons:
-Sing Out
-Search Bar
•⁠  ⁠Cart Button
•⁠  ⁠Seller Center (Only if the user is a Seller)
-Settings
It is not a requirement for this delivery that the buttons have functionality, but they must be prepared to have it. Follow the design by Luis Hernández.

Completion Criteria:
Submit a page with all the requirements mentioned. Push a file containing the coded page to the web UI branch. User is able to view Home Page UI.

Time Constraint:
 
    Complete by Friday, September 13th, 2024.
 
Difficulty Score: 4
 
Urgency Score: 5

**Comment by NatiPerez459** [comment]
![image](https://github.com/user-attachments/assets/ba88a9c8-9cad-4886-98fd-58746d5ab3ae)
![image](https://github.com/user-attachments/assets/01c9c281-be4d-4cf5-93f8-756f3e1bb3f9)
