### ISSUE TITLE
Seller Center Page Code UI

### ISSUE THREAD

**Issue by CdoxHype** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#53]
Requirements:
This page must have the following at a minimum:
 
•⁠  ⁠A history of products (Listed, Sold, Drafts).
•⁠  ⁠Basic Statistics section (It should not work in this delivery, but it should be an option available for when it is implemented).
•⁠  ⁠Button to return to the home page.
•⁠  ⁠Button to go to the product listing page.
 
More functionalities can be added. It is not a requirement for this delivery that the buttons have functionality, but they must be prepared to have it.

Completion Criteria:

Submit a page with all the requirements mentioned. Push a file containing the coded page to the web UI branch’.

Time Constraint:
 
    Complete by Friday, September 13th, 2024.
 
Difficulty Score: 5
 
Urgency Score: 6

**Comment by Kaariinaa08** [comment]
![Screenshot_13-9-2024_204725_localhost](https://github.com/user-attachments/assets/15995181-3d39-4d1f-86b5-821db62f7329)

**Comment by Kaariinaa08** [comment]
"Seller Dashboard UI" file was pushed to "Website-Frontend" Branch.
