### ISSUE TITLE
Environment variables and dependency setup

### ISSUE THREAD

**Issue by JadStelar** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#55]
Objective: Introduce the usage of environmental variables into the repository, install tools that allow access and usage to environment variables, and document the standard for future environment variables and their usage. Document local dependency installation procedure and remove current dependencies installed in the repository.

Requirements:
The Tech Stack document details the standard for environment variable and how to use them.
All current/future API keys and credentials are redefined as environment variables. Local installation procedure for dependencies, which will improve runtime of builds, commits, etc.

Subtasks:
- [x] Introduce environment variables and related tools into the repository.
- [x] Update current repository to match these specifications.
- [x] Document the usage of environment variables in the tech stack document.
- [x] Document the steps to locally download all needed dependencies.

Completion Criteria:

The successful installation of tools to use environment variables in code. Documentation on how to setup .env files and how to locally download dependencies needed to run. No dependencies installed in the repository.

Time Constraint:

Completed by Wednesday, September 11th

Scoring:
Urgency: 3
Difficulty: 5

**Comment by fduffoo** [comment]
Hey there, I would like to work on this if you could assign it to me!

**Comment by JadStelar** [comment]
Hey, I've almost done with the documentation substasks. If you'd like you can work on removing the index.js file and node_modules in the node.js_base_server branch, updating .gitignore (see main branch), and downloading dotenv in that branch. All these should also be done where applicable in the sign-up/login branch

**Comment by JadStelar** [comment]
Documented environment variable standard usage and setup, alongside dependency setup in the tech stack document found [here](https://docs.google.com/document/d/1Bg0lHtuzFIWX4ny9sntZGf4Mncs9wMP5t9Bogsy2hkQ/edit?usp=sharing), as well as in a discussion named "Environment variables".
