### ISSUE TITLE
Develop and Implement Controller for Item Schema  

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#59]
Objective:  
Develop a controller for the Item schema that will handle all CRUD operations (Create, Read, Update, Delete) for managing products within the application.

Requirements:

- Implement methods for adding, retrieving, updating, and deleting product records.
- Ensure thorough validation and error handling for each operation.

Completion Criteria:

- Full CRUD functionality for the Item schema is developed and operational.
- The controller successfully manages errors and validates input data.

Time Constraint:  
Target completion by Thursday, September 12.

Scoring:  
Difficulty: 5 
Urgency: 5

**Comment by AlvinBadillo** [comment]
I have completed the following parts of the task:

Create Item: Implemented the createItem method with validation to ensure proper data input, and error handling to catch and log any issues.

Get All Items: Developed the getAllItems method, which retrieves and returns a list of all items from the database, with error handling for potential issues.

Get Item by ID: Created the getItemById method, which fetches a specific item based on its ID. It handles errors for invalid IDs or if the item is not found.

Each method ensures validation and error management, aligning with the task's requirements.

**Comment by JoshDG03** [comment]
I completed the following parts of the task 

Update an Item by ID: implemented the updateItemById method which also has validation and error handling like the createItem method. 

Delete Item by ID: implemented the deleteItemById method which searched for an Item and handles situations in which the item is not found, if it is deleted succesfully or the item was not able to be deleted. 

The methods ensure validation and error handling as required by the task.
