### ISSUE TITLE
Duplicate Account Prevention

### ISSUE THREAD

**Issue by FabiolaZTorres** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#61]
Objective:

- Validate whether the username or email address entered by a user when signing up are already in use within the database. Since both are key account identifiers, they must be unique.

Requirements:

- The backend logic should include a check for duplicate accounts when a user attempts to sign up.

Completion Criteria:

- The system should prevent accounts from being created with usernames and/or emails that are already in the database.
- A clear, user-friendly error message should be displayed to notify the user when they attempt to use an existing email or username (e.g., "This email/username is already registered. Please use a different one or log in.").

Difficulty: 4
Urgency: 3

**Comment by F3rnand0hr** [comment]
Duplicate prevention logic implemented but couldn't be tested since back-end is not connected to the front-end.
