### ISSUE TITLE
Creation of Mercado Colegial Online Interest Form

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#62]
Objective:
The creation of an interest form or Google form to gather vendor interest on the project is essential to the project's success. Measuring vendor interest and wilingness to participate is crucial for developing the system further. The survey should also include questions that help further define the project domain.

Requirements:
Creation of a survey for gathering vendor interest in the project

Completion criteria: 
Succesful creation of the survey to gather vendor interest and data

Scoring:
Urgency: 4
Difficulty: 3

Time constraint: September 18

**Comment by cristian-barreras** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSe-7v7oCbiCrnhRQbMrvl1VbrHAgN5fdCW4T09SFNNwzFPayA/viewform?usp=sf_link

**Comment by cristian-barreras** [comment]
In my top comment is the link to the interest forum. Eventually we should create an official mercado colegial email for this project and pass this forum to that email.
