### ISSUE TITLE
Database Design: Item Model Creation

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#67]
Objective:

- Design and implement the Item entity model to align with the overall database structure and ensure robust data management.

Requirements:

- Design the Item Entity: Define the structure of the Item entity, ensuring that it supports all required fields and relationships.

- Define Parameters: Assign discussed parameters in the ERD to the Item entity, considering data types, constraints, and relationships to other entities.

Completion Criteria:

- The Item entity model is fully defined, implemented, and integrated with the database.

- The model includes all fields, data types, and constraints specified in the initial ERD.

Time Constraint:

- Deadline: Thursday, September 12

Scoring:

- Urgency: 6

- Difficulty: 3

**Comment by JuanIranzo** [comment]
Local branch has been pushed, waiting on merge to the DB team branch. Item model was created succesfully, Item parameters were added to the model. Important to note that the model is still subject to change depending on how the database schema grows. Additionally, installed mongoose and body-parser packages for entity creation (specifically mongoose). Next step is to implement the controller for the Item model.

**Comment by YampierFernandez** [comment]
Checked and approved for manger review.
