### ISSUE TITLE
Database Design: User Model Creation

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#68]
Objective:

- Design and implement the User entity model to align with the overall database structure and ensure robust data management.

Requirements:

- Design the User Entity: Define the structure of the User entity, ensuring that it supports all required fields and relationships.

- Define Parameters: Assign relevant attributes based on the ERD, considering data types, constraints, and relationships to other entities.

Completion Criteria:

- The User entity model is fully defined, implemented, and integrated with the database.

- The model includes all fields, data types, and constraints specified in the initial ERD.

Time Constraint:

- Deadline: Thursday, September 12

Scoring:
Urgency: 6/10
Difficulty: 3/10

**Comment by Cabinetman** [comment]
Implemented the user model with relevant attributes.

**Comment by YampierFernandez** [comment]
Checked and approved for manger review.
