### ISSUE TITLE
Implement Email Confirmation for User Registration

### ISSUE THREAD

**Issue by jonael-garcia26** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#70]
Objective:

Design and start implement an email confirmation feature to enhance user registration and ensure account activation.

Requirements:

1. Email Confirmation Workflow:

- Implement a system to send a confirmation email to users upon registration.

- The email should include a unique confirmation link that the user must click to activate their account.

2. Confirmation Link:

- Generate a unique, secure token for each confirmation link.

4. Email Template:

- Design and implement a user-friendly email template for the confirmation message.

- Ensure the email includes clear instructions and a working confirmation link.

Completion Criteria:

- The email confirmation feature is mostly implemented.

- Select a service for sending emails.

Time Constraint:

- Deadline: Friday, October 25

Scoring:

- Urgency: 5/10

- Difficulty: 6/10

**Comment by F3rnand0hr** [comment]
We still have to link the confirmation to the backend to make it so if the account is not yet verified, user can't log in. The data base isn't fully implemented so we can't link the users emails, and usernames. Since we can't implement these features, testing will be not be possible.
