### ISSUE TITLE
Documentation - 2.1.1 Domain rough sketch

### ISSUE THREAD

**Issue by Christian2101** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#73]
Objective: Complete out section 2.1.1 Domain rough sketch.

- The domain rough sketch refers to an application: the domain is that part of the observable universe that is of interest to your project, but independent of a system-to-be. Rough sketches are for collecting unprocessed information for example from brainstorming sessions, interviews, literature review, … Your domain description rough sketch mentions the application you intend to create: that's not part of the domain.

Requirements:

-Ensure that section 2.1.1 of the documentation is completely filled out.

- Ensure to define completely how a system should interact with and represent the real-world domain.

Completion Criteria:

-The required section is filled out by specifying the above mentioned requirements of the Domain rough sketch

Time Constraint: Friday September 20

Urgency: 8
Difficulty: 5

**Comment by YampierFernandez** [comment]
Basic domain elements:

-The UPRM
-students 
-buyers 
-sellers
-Present “Mercado collegial”
-websites
-online shopping 
-profiles
-carts 
-ordering
-reviews
-catalogs
-User interfaces

...more will be added if identified

This comment is here to help organize ideas

**Comment by YampierFernandez** [comment]
Mercado Colegial takes place typically once a month in the UPRM campus. It's an event for UPRM students or trustworthy people to set up little stands and sell things like: dresses, fruits, vegetables, cakes, cookies, candies, necklaces, bracelets, handmade soap, art, stickers, crafts and many more. 

Mercado Colegial is not only a place for shopping but a fun activity for students and a good place for announcements, talks, music, and more.

What if Mercado Colegial could be active more than just once a month? 

Why not make shopping even more convenient?

Few things have made shopping better and easier than online stores like eBay, amazon and Etsy. In these websites you make your profile and have access to a large market that lets you buy or sell just by using a phone, tablet or computer. 
Going through a catalog or just searching for something specific, making a list of wanted items (cart), and conveniently paying for the order on a personal device is quicker and easier for anyone. 

Websites can also provide reviews, purchase history, product tracking, announcements, ads and other information to their users.

**Comment by YampierFernandez** [comment]
2.1.1 Domain rough sketch:

Mercado Colegial takes place typically once a month in the UPRM campus. It's an event for UPRM students or trustworthy people to set up little stands and sell things like: dresses, fruits, vegetables, cakes, cookies, candies, necklaces, bracelets, handmade soap, art, stickers, crafts and many more. 

Mercado Colegial is not only a place for shopping but a fun activity for students and a good place for announcements, talks, music, and more.

What if Mercado Colegial could be active more than just once a month? 

Why not make shopping even more convenient?

Few things have made shopping better and easier than online stores like eBay, amazon and Etsy. In these websites you just make your profile and gain access to a large market that lets you buy or sell just by using a phone, tablet or computer. 

Going through a catalog or just searching for something specific, making a list of wanted items (cart), and conveniently paying for the order on a personal device is quicker and easier for anyone. 

Websites can also provide reviews, purchase history, product tracking, announcements, ads and other information. And best of all, typically these websites are always available.

The features of an online website could do a lot of good to Mercado Colegial.



**This is my submission for the Domain rough sketch**

**Comment by YampierFernandez** [comment]
**The comment above is my submission for the Domain rough sketch**
