### ISSUE TITLE
Documentation - 2.1.2 Terminology and 2.1.3 Domain Terminology in relation to domain rough sketch

### ISSUE THREAD

**Issue by Christian2101** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#74]
Objective: Complete out sections 2.1.2 Terminology and 2.1.3 Domain Terminology in relation to domain rough sketch.

-Terminology:  What are the actions that can be performed with these entities? Events?  Behaviors?. 

-Domain Terminology in relation to domain rough sketch: The domain terminology is not part of the rough sketch: to develop the terminology you have to analyze the rough sketch and come up with good definitions for the terms used e.g. in stakeholder interviews. So, the definitions are results of the processing and are therefore not rough.

Requirements:

-Ensure that section 2.1.2 and 2.1.3 of the documentation is completely filled out.

Ensure to identify and define completely and correctly all Terminology present within the project.

Completion Criteria:

-The required section is filled out by specifying the above mentioned requirements of the required sections.

Time Constraint: Friday September 20

Urgency: 8
Difficulty: 5

**Comment by CovasJJ** [comment]
Completed Task. I successfully filled out sections 2.1.2 (Terminology) and 2.1.3 (Domain Terminology in relation to the domain rough sketch).  I defined key terminology and other domain terminology related to the domain rough sketch.
