### ISSUE TITLE
Documentation - 1.2.2 Needs

### ISSUE THREAD

**Issue by elliot-gomez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#77]
Objective:
Clearly define the needs arising from the current situation, focusing on the problems or requirements of the stakeholders independently of the system-to-be. The goal is to help developers understand the fundamental needs of users without proposing solutions yet.

Needs
- Describe the needs of stakeholders or users based on the current situation. Focus on what they require in the domain, not the specific features or implementation of the system.
- Ensure the needs are distinct from any solutions or ideas you might have for solving them. For example, a need could be for easier access to information or simplified processes, rather than how your system will achieve this.
- Mention needs related to other parts of the project, such as domain description, requirements, software architecture, and test planning.

Requirements:
- The section should clearly explain the problems or requirements that need to be addressed without referencing specific solutions.
- Ensure that needs are defined in a way that is independent of the system-to-be, making them applicable to the general domain.
- Include any relevant external needs (domain descriptions, requirements, software architecture) that are crucial for project success.

Completion Criteria:
- Section 1.2.2 (needs) of the project documentation is fully written and clearly communicates the needs of stakeholders or users in the current situation, without prematurely introducing system solutions or features.

Time Constraint: Complete by Friday, September 20th

Urgency: 8
Difficulty: 5

**Comment by JoshDG03** [comment]
We clearly identified the needs for all parties in the domain of this project. The needs are clearly outlined for the developers to work on, and no solutions are proposed.

**Comment by elliot-gomez** [comment]
When you have a chance, please review it and let me know if any changes are needed. Thanks!
