### ISSUE TITLE
Documentation - 1.5 Derived Goals

### ISSUE THREAD

**Issue by elliot-gomez** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#80]
Objective:
Identify and document secondary goals of the project that are distinct from the primary goals described in the earlier sections, such as current situation, needs, and ideas. These goals should reflect additional desirable outcomes that the project aims to achieve beyond its core objectives.

Derived Goals
- List secondary goals that are separate from the primary project goals identified in sections like current situation, needs, and ideas.
- Ensure these goals are significantly different from the core objectives and not just extensions of the primary goals.
- For example, if the primary goal is to solve a technical problem, a secondary goal could involve raising awareness of the issue or fostering collaboration between stakeholders.

Requirements:
- Clearly outline secondary, desirable outcomes of the project, ensuring they differ from the primary goals.
- Describe how these secondary goals align with or complement the overall objectives of the project.
- Avoid reiterating the primary goals from earlier sections.

Completion Criteria:
- Section 1.5 (derived goals) of the project documentation is fully written, listing secondary goals that are distinct from primary goals and explaining how these secondary outcomes add value to the project.

Time Constraint: Complete by Friday, September 20th

Urgency: 8
Difficulty: 5

**Comment by Christian2101** [comment]
Task Completed:

Completed section 1.5 providing desirable secondary outcomes of the project, ensuring they differ from the primary goals.
Described how these secondary goals align with or complement the overall objectives of the project.
