### ISSUE TITLE
Research Pass and secrets.js

### ISSUE THREAD

**Issue by ActuallySeb** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#84]
Objective:

Learn more about Pass, the standard UNIX password manager, to securely manage and use secrets in the project.

Requirements:

Read through the official Pass documentation, tutorials, and any relevant posts. Understand and document key features, setup process, secret management workflow, and potential use cases for the project. Gather feedback from team leader, TAs, or professor on information learned and receive approval on correctness and viability of using Pass in the project.

Completion Criteria:

Create a document summarizing findings, with a section for setup steps, usage examples, recommended practices, and references.

Time Constraint:

Completed by Friday, October 4th

Urgency: 6
Difficulty: 2

**Comment by JadStelar** [comment]
I have compiled all findings into the following document:
https://docs.google.com/document/d/1pfMHJR785Zl-pwveD7P5dhJtOExd70e-Zk4lWENgQi8/edit?usp=sharing
