### ISSUE TITLE
Documentation - 2.1.4 Narrative

### ISSUE THREAD

**Issue by Cabinetman** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#88]
Objective: Finish part 2.1.4 domain narrative

•The domain narrative tells the story of the domain. The domain is that part of the universe of interest to your project but independent of the system-to-be. Anything that talks about the "application" is not part of domain narrative, therefore, "homepage", "navigation bar" etc. have no place here. You can describe these where you start talking about the actual implementation. Also, in domain narrative you want to talk about the domain not about using the application.

Requirements:

•Ensure that section 2.1.4 of the documentation is completely filled out.
•Ensure that the domain narrative reflects the actual phenomena, entities, and relationships of the universe being modeled, free from references to system design or implementation.

Completion Criteria:

•The required section is filled out by specifying the above-mentioned requirements of the Domain rough sketch

Time Constraint: Friday September 20

Urgency: 10
Difficulty: 4

**Comment by JuanIranzo** [comment]
The section 2.1.4 of the documentation, which corresponds to the Narrative has been written and added to the document, adhering to guidelines and requirements for the section

**Comment by Cabinetman** [comment]
Revised and corrected a few more things to the narrative section of the documentation so it should be good to go.
