### ISSUE TITLE
Milestone Documentation 2.1.5 Events, Actions, and Behaviors

### ISSUE THREAD

**Issue by NatiPerez459** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#96]
# Objective
Complete the section 2.1.5 Events, Actions, and Behaviors of the Milestone 1 documentation following the established guidelines and evaluation criteria. Ensure the section is properly formatted according to documentation structure previously established. Section must contain and describe the Actions, Events, and Behaviors for the domain description.

# Requirements
 - Events: The moment when the user has just completed an action. (Ex. Becoming a member)
 - Actions: The act taken towards making the event. (Ex. The act of becoming a member)
 - Behaviors: Smaller actions that make together the purpose of the event. (Ex. Smaller actions that make up "becoming a member")
 - Follow established milestone guidelines.
 - Follow documentation structure previously established.

# Completion Criteria
Completed section 2.1.5 of the documentation milestone follow established guidelines and documentation format.

# Timeline
September 20th, 2024

**Comment by YampierFernandez** [comment]
2.1.5 Events, actions, and behaviors
Actions:
-A user is accessing the Mercado Colegial Online website.
-The user is browsing through the catalog of available items.
-The user is adding items to their shopping cart.
-The seller is updating their shop with new products.
-The user is checking out and completing a purchase.
-The system is updating the inventory after the purchase.

Events:
-The user finds an item they want to purchase.
-The user adds an item to the cart.
-The item information (e.g., price, description) is displayed.
-The inventory of an item is updated in real-time.
-An item is sold through the online platform.
-An item goes out of stock.
-Sellers receive notifications for low stock or out-of-stock items.

Behaviors:
-A user searches for a specific item or category.
-A seller adds or removes items from their online shop.
-The buyer compares items based on reviews or seller ratings.
-A buyer completes a purchase transaction online.
-The system notifies the user of successful payment and estimated delivery or pickup details.
-Sellers adjust prices or add discounts based on demand or event promotions.
