### ISSUE TITLE
Team Lead Task - Monitor Database Team Performance

### ISSUE THREAD

**Issue by NatiPerez459** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#98]
## Objective:
•	Conduct meetings with the Database team, review completed assignments and overlook members activity throughout the Milestone maintaining documentation of accomplished activities guiding the database team towards success.

## Requirements:
•	Conduct weekly meetings with the Database team to establish sprint goals, discuss progress and ideas for future assignments.
•	Review completed assignments from team members to ensure they follow established requirements and guidelines.
•	Review created code and ensured it complies with the requirements and passes test cases with the expected output.
•	Maintain documentation of progress and established individual goals for the Milestone.

## Completion Criteria:
•	Created record of meeting recordings, and minutes of important details discussed in meetings.
•	All completed assignments have been reviewed and tagged with Lead Reviewed labels.
•	Completed documentation of progress completed by individual team members and comparison of accomplishments with established team goals.

## Time Constraint:
•	End of Milestone 2: October 25, 2024

## Scoring:
•	Urgency: ?
•	Difficulty: ?

**Comment by YampierFernandez** [comment]
[DB Doc.pdf](https://github.com/user-attachments/files/17527441/DB.Doc.pdf)

**Comment by YampierFernandez** [comment]
https://github.com/user-attachments/assets/d5a332b2-96c8-4b12-a1fb-91741732410a

Meeting recording


Important details:
- 4:04-5:35
- 9:10-final
