### ISSUE TITLE
Database Design: Sell Action Creation

### ISSUE THREAD

**Issue by JuanIranzo** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#99]
Objective:

Design and implement the Sell action table to align with the overall database structure and ensure robust data management.
Requirements:

Design the Sell Action: Define the structure of the action Sell, ensuring that it supports all required fields and relationships.

Define Parameters: Assign discussed parameters in the ERD to the Sell action, considering data types, constraints, and relationships to other entities.

Completion Criteria:

The Sell action table is fully defined, implemented, and integrated with the database.

The model includes all fields, data types, and constraints specified in the initial ERD.

Time Constraint:

Deadline: Thursday, October 3
Scoring:

Urgency: 6

Difficulty: 4

**Comment by JuanIranzo** [comment]
Branch was pushed on Friday, forgot to post update here. Sell action entity implemented, branch is called Database-sell-implementation

**Comment by YampierFernandez** [comment]
Checked model created by Juan in sell_item_implementation. Approved for manager review.
